### ISSUE TITLE
Research: As a Site Editor, is there a way to export the details of the content on the site for review purposes

### ISSUE THREAD

**Issue by aleayr** [govCMS/staysmartonline_theme#11]
# Full Description

For exporting content/nodes information (such as title, URL, etc) for facilitating an offline content review.
# Acceptance Criteria

Please provide advice on whether this is possible and how to achieve.

**Comment by invisigoth** [comment]
This will most likely be something a custom View can provide. Given their site only has less than 300 content pages, setting up a view for reporting purpose without pagination will not be too much of a concern either. It is however advisable that the client takes a copy of the site and set up the view/report in a non-production environment.
