### ISSUE TITLE
Research: Stay Smart Online Google Analytics code not reporting data

### ISSUE THREAD

**Issue by aleayr** [govCMS/staysmartonline_theme#12]
# Full Description

The Google Analytics UA code has been entered into the Stay Smart Online website, however, it is not reporting data.  Can we investigate as to why this might be the case?
# Acceptance Criteria

Data flowing back into Google Analytics for Stay Smart Online.

**Comment by teamglenny** [comment]
Global govCMS code _is_ tracking data.  Suggest SMO double/triple check their GA configuration to ensure it is pointing to the right place.

**Comment by aleayr** [comment]
Looks like an issue with still using the Comms custom config designed for having Google Tag Manager. Removed it, so hopefully will start working. Have offered our stats to be exported when they want some numbers.
