### ISSUE TITLE
Remove users from Dept of Communications

### ISSUE THREAD

**Issue by aleayr** [govCMS/staysmartonline_theme#2]
# Full Description

The full list of users in the People tab makes administration more difficult.
# Acceptance Criteria

All Communications staff to be removed from the platform. Stay Smart Online notes and accepts the revision history (pre transition) will default to 'Anon User'.

**Comment by invisigoth** [comment]
We have not long ago disabled the "remove" user function on govCMS and can only "block" users. All Comms users on the site are already block.
