### ISSUE TITLE
Research: As a site editor, how do I edit the 'For more: Alerts / Newsletter' section on the front page of the website

### ISSUE THREAD

**Issue by aleayr** [govCMS/staysmartonline_theme#9]
# Full Description

Can't discover where the ability to edit this section has been setup, so it can be easily edited.
# Acceptance Criteria

A response provided to Stay Smart Online about how to edit this section.

**Comment by invisigoth** [comment]
This section is implemented as a block and can be modified at:

https://www.staysmartonline.gov.au/block/sso-online-alerts-heading/edit
